### ISSUE TITLE
serve namespace files

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/valueflo.ws#10]
hey @elf-pavlik, can you explain what files (and formats) should be in [the `ns` directory](https://github.com/valueflows/valueflo.ws/issues/7)? i'm happy to get continuous deployment setup across all our repos so a push to anywhere deploys the namespace files at https://valueflo.ws (so we can migrate away from using rawgit), but i'm not sure what files should be there.

also, to clarify, this question is not about serving these files, just building (assembling) them, as i want to keep those steps separate.

**Comment by elf-pavlik** [comment]
In the end we should support [Content Negotiation](https://en.wikipedia.org/wiki/Content_negotiation), but that goes into how we serve content. So for now I think enough if content of Person.md from agent repo will appear rendered to HTML on https://valueflo.ws/ns/Person
No sure if that answers your question....

**Comment by ahdinosaur** [comment]
a better way to ask my question: what should be returned by:

```
curl -L https://w3id.org/valueflows/ -H "Accept: application/ld+json"
```

and similarly:

```
curl -L https://w3id.org/valueflows/Person -H "Accept: application/ld+json"
```

?

**Comment by fosterlynn** [comment]
> so a push to anywhere deploys the namespace files at https://valueflo.ws (so we can migrate away from using rawgit)

@ahdinosaur awesome!

Maybe a question for later when we have enough to be "production": how do we best keep "development" and "production" versions separate?  I think a lot of things will be pushed that are not ready for prime time.

**Comment by ahdinosaur** [comment]
@fosterlynn for that i recommend we version our vocabs with [semver](http://semver-ftw.org/), so each version (including separate branches for latest 'production' versus new 'development') can be retrieved independently, but yeah that's probably a detail for later.

**Comment by elf-pavlik** [comment]
this part already works

```
curl -iL https://w3id.org/valueflows/Person -H "Accept: application/ld+json"
HTTP/1.1 303 See Other
Location: http://valueflo.ws/Person
```

BTW we should to change it to HTTPS in next PR to w3id.org!

Next step 

```
curl -iL https://velueflo.ws/Person -H "Accept: application/ld+json"
HTTP/1.1 303 See Other
Location: http://valueflo.ws/
```

Which IMO if "application/ld+json" requested should return the JSON-LD contex which currently also includes all the RDFS/OWL definitions of vf vocabulary (which includes also vf:Person) :smile: 

if "text/html" requested it will not do another 303 but simply 200 for human to enjoy jolly text, well formatted examples and colorful diagrams :exclamation: 

Before we go 1.0 I'll ask around about recommendations for chaining 303 or 302 redirects.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflo-ws/-/issues/10.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
