### ISSUE TITLE
building examples

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/valueflo.ws#11]
how do we want to build our examples into our website?

for me: i'm thinking in the short-term we want to copy the '.jsonld' files to https://valueflo.ws/examples/ simply so they can reference each other without using rawgit. in the long-term, i imagine it'd be really sweet to have our examples standardized into some semantic format ([skos documentation](http://www.w3.org/TR/skos-reference/#notes)?) and integrated with our docs, possibly even automatically viewed with JSON-LD playground.

**Comment by fosterlynn** [comment]
@ahdinosaur good thoughts.  I was starting to integrate examples into the md file just with links, but can change that to whatever works for your website creation scripts.  See this as an example too: http://www.w3.org/TR/activitystreams-vocabulary/#dfn-relationship - maybe farther down the road than the skos doc format.

**Comment by bhaugen** [comment]
@ahdinosaur - once the examples get formalized enough, let's also develop code examples that produce and consume them. If you develop any code that might go in that direction, please think about how we can include it along with the json-ld examples. (Same for @fosterlynn - we should see if we can carve out some python examples from your agent work.)

**Comment by fosterlynn** [comment]
@bhaugen totally agree, it will be 1000 times easier for developers to adapt vf if there are code examples in different languages.  I'll carve from NRP (python and rdflib example) when it works.....  :)

**Comment by ahdinosaur** [comment]
> it will be 1000 times easier for developers to adapt vf if there are code examples in different language

yes yes yes. developers i've spoken with so far even want the next step: code _libraries_ to use `vf`.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflo-ws/-/issues/11.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
