### ISSUE TITLE
Website certificate errors

### ISSUE THREAD

**Issue by nogo10** [valueflows/valueflo.ws#12]
It seems the valueflo.ws website generates expired certificate errors blocking access to the site. 

 >Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by fosterlynn** [comment]
@nogo10 thanks much for reporting it, we know and are working on it (slowly).  In the meantime, try www.valueflo.ws, that should work for you.  Sorry for the inconvenience!

**Comment by almereyda** [comment]
This has been resolved.
