### ISSUE TITLE
Any large version of the UML diagram ?

### ISSUE THREAD

**Issue by tfrancart** [valueflows/valueflo.ws#13]
The image at https://valueflo.ws/specification/diagrams/uml.html is really small, to the point of being useless, and I can't find any pointer to a larger version. It is however a key entry point to anyone wanting to understand the vocabulary.

**Comment by tfrancart** [comment]
OK found out that this is probably replaced by the other valueflow repository, and found larger version of the diagram at https://camo.githubusercontent.com/dd1ad45e44a27a42b663c968a8a756e954847ca3/68747470733a2f2f7261776769742e636f6d2f76616c7565666c6f77732f76616c7565666c6f77732f6d61737465722f72656c656173652d646f632d696e2d70726f636573732f56616c7565466c6f7773554d4c2e706e67

**Comment by fosterlynn** [comment]
Thanks @tfrancart !  You are right it is too small!

You can also right click and choose View image, and you will get a bigger one.  We will at least put that into the text there.  Or find a better way, like your link.

Thanks again!

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflo-ws/-/issues/13.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
