### ISSUE TITLE
rename to `openvocab.github.io`

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/valueflo.ws#2]
i like this idea of having a website repo for our vocab which includes the `context.jsonld`. if we rename this repo to `openvocab.github.io`, then GitHub will host the `master` branch as a website at that URL (which we can CNAME to a different URL once we decide on https://github.com/openvocab/agent/issues/23).

**Comment by fosterlynn** [comment]
@ahdinosaur beyond my skillset, so I'm glad you are on it!

**Comment by ahdinosaur** [comment]
i'll take that to mean you're okay with me renaming this repo. let me know if that's not okay.
