### ISSUE TITLE
URL structure

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflo.ws#7]
Currently I see at least two categories of content which we may want host on valueflo.ws
### vocab terms

particular terms which https://w3id.org/valueflows/ will redirect to eg. https://w3id.org/valueflows/Transfer
### general documentation

wiki style documentation which explains some pattern in more depth, often not specific to a single term eg. 'Multilingual Content'
### deep path
- https://valueflo.ws/ns/Transfer
- https://valueflo.ws/docs/multilingual
### subdomain
- https://valueflo.ws/Transfer
- https://docs.valueflo.ws/multilingual
### path exception - docs
- https://valueflo.ws/Transfer
- https://valueflo.ws/docs/multilingual

this one would have https://valueflo.ws/docs/ which doesn't map to a property or class

**Comment by ahdinosaur** [comment]
:+1: for deep path option. also might be worth mentioning that i envision our docs being markdown files in [valueflows/valueflows](https://github.com/valueflows/valueflows), which are built into html files and pushed to this repo.

**Comment by fosterlynn** [comment]
Yes, I do have on my list to add to the md file for Agent.  Will try to get to today.

Although I will say that I'm probably more comfortable in html than in markdown. 

At a certain level of complexity, might be easier to just maintain it in html?

Re. the options, you guys decide, it's above my pay grade.  :)

**Comment by bhaugen** [comment]
@fosterlynn - I think we should stick with markdown. Sorry about that...:wink:

**Comment by fosterlynn** [comment]
@bhaugen Ha, no problem, you are allowed to disagree!  I'm sticking with md for now in any case..... :wink:

**Comment by ahdinosaur** [comment]
@elf-pavlik: does this mean we should change https://w3id.org/valueflows/ to point to https://valueflo.ws/ns/?

**Comment by elf-pavlik** [comment]
@ahdinosaur once we start responding there with something else than "Cannont GET ..." we should update the redirect, until then it doesn't really matter since all the data uses permanent  https://w3id.org/valueflows/ prefix.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflo-ws/-/issues/7.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
